// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps(created_at, updated_at, body, user_id) VALUES (
    NOW(), NOW(), $1, $2
) RETURNING id, user_id, created_at, updated_at, body
`

type CreateChirpParams struct {
	Body   string
	UserID int32
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
	)
	return i, err
}

const deleteAllChirps = `-- name: DeleteAllChirps :exec
DELETE FROM chirps
`

func (q *Queries) DeleteAllChirps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChirps)
	return err
}

const deleteChirp = `-- name: DeleteChirp :exec
DELETE FROM chirps WHERE id = $1
`

func (q *Queries) DeleteChirp(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteChirp, id)
	return err
}

const deleteChirp2Step = `-- name: DeleteChirp2Step :exec
DELETE FROM chirps WHERE id = $1 AND user_id = $2
`

type DeleteChirp2StepParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteChirp2Step(ctx context.Context, arg DeleteChirp2StepParams) error {
	_, err := q.db.ExecContext(ctx, deleteChirp2Step, arg.ID, arg.UserID)
	return err
}

const deleteChirpsByUserId = `-- name: DeleteChirpsByUserId :exec
DELETE FROM chirps WHERE user_id = $1
`

func (q *Queries) DeleteChirpsByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteChirpsByUserId, userID)
	return err
}

const getAllChirps = `-- name: GetAllChirps :many
SELECT id, user_id, created_at, updated_at, body FROM chirps
`

func (q *Queries) GetAllChirps(ctx context.Context) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChirp = `-- name: GetChirp :one
SELECT id, user_id, created_at, updated_at, body FROM chirps WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id int32) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
	)
	return i, err
}
