// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Chirp struct {
	ID        int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
}

type RefreshToken struct {
	Token     string
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             int32
	CreatedAt      time.Time
	UpgradedAt     time.Time
	Email          string
	HashedPassword string
}
