// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Chirp struct {
	ID        int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
}

type User struct {
	ID         int32
	CreatedAt  time.Time
	UpgradedAt time.Time
	Email      string
}
