// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addRefreshToken = `-- name: AddRefreshToken :one
INSERT INTO refresh_tokens(token, user_id, expires_at, revoked_at, created_at, updated_at)
VALUES($1, $2, $3, $4, NOW(), NOW()) RETURNING token, user_id, created_at, updated_at, expires_at, revoked_at
`

type AddRefreshTokenParams struct {
	Token     string
	UserID    int32
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, addRefreshToken,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.RevokedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenToken = `-- name: GetRefreshTokenToken :one
SELECT token, user_id, created_at, updated_at, expires_at, revoked_at FROM refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefreshTokenToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefreshTokenUser = `-- name: GetRefreshTokenUser :one
SELECT token, user_id, created_at, updated_at, expires_at, revoked_at FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) GetRefreshTokenUser(ctx context.Context, userID int32) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenUser, userID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const resetRefreshToken = `-- name: ResetRefreshToken :exec
DELETE FROM refresh_tokens
`

func (q *Queries) ResetRefreshToken(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRefreshToken)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens SET revoked_at = $2 WHERE token = $1
`

type RevokeTokenParams struct {
	Token     string
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeToken, arg.Token, arg.RevokedAt)
	return err
}
